/**
 * themes.js — Color theme definitions.
 *
 * Each theme defines CSS custom properties that are applied to <html>.
 * Components use these via Tailwind arbitrary values: bg-[var(--color-primary)]
 */

export const THEMES = [
    {
        id: 'blue',
        name: 'Xanh dương',
        color: '#2563eb',
        vars: {
            '--color-primary': '#2563eb',
            '--color-primary-hover': '#1d4ed8',
            '--color-primary-light': '#eff6ff',
            '--color-primary-medium': '#dbeafe',
            '--color-primary-dark': '#1e40af',
            '--color-primary-ring': '#3b82f6',
            '--color-gradient-from': '#6366f1',
            '--color-gradient-to': '#8b5cf6',
            '--color-msg-sent': '#2563eb',
            '--bg-main': '#eff6ff',
            '--bg-card': '#ffffff',
            '--bg-secondary': '#dbeafe',
            '--bg-input': '#ffffff',
            '--bg-hover': '#dbeafe',
            '--text-primary': '#111827',
            '--text-secondary': '#374151',
            '--text-tertiary': '#6b7280',
            '--border-color': '#bfdbfe',
            '--border-input': '#93c5fd',
        },
    },
    {
        id: 'red',
        name: 'Đỏ',
        color: '#dc2626',
        vars: {
            '--color-primary': '#dc2626',
            '--color-primary-hover': '#b91c1c',
            '--color-primary-light': '#fef2f2',
            '--color-primary-medium': '#fee2e2',
            '--color-primary-dark': '#991b1b',
            '--color-primary-ring': '#ef4444',
            '--color-gradient-from': '#ef4444',
            '--color-gradient-to': '#f97316',
            '--color-msg-sent': '#dc2626',
            '--bg-main': '#fef2f2',
            '--bg-card': '#ffffff',
            '--bg-secondary': '#fee2e2',
            '--bg-input': '#ffffff',
            '--bg-hover': '#fee2e2',
            '--text-primary': '#111827',
            '--text-secondary': '#374151',
            '--text-tertiary': '#6b7280',
            '--border-color': '#fecaca',
            '--border-input': '#fca5a5',
        },
    },
    {
        id: 'purple',
        name: 'Tím',
        color: '#9333ea',
        vars: {
            '--color-primary': '#9333ea',
            '--color-primary-hover': '#7e22ce',
            '--color-primary-light': '#faf5ff',
            '--color-primary-medium': '#f3e8ff',
            '--color-primary-dark': '#6b21a8',
            '--color-primary-ring': '#a855f7',
            '--color-gradient-from': '#a855f7',
            '--color-gradient-to': '#ec4899',
            '--color-msg-sent': '#9333ea',
            '--bg-main': '#faf5ff',
            '--bg-card': '#ffffff',
            '--bg-secondary': '#f3e8ff',
            '--bg-input': '#ffffff',
            '--bg-hover': '#f3e8ff',
            '--text-primary': '#111827',
            '--text-secondary': '#374151',
            '--text-tertiary': '#6b7280',
            '--border-color': '#e9d5ff',
            '--border-input': '#d8b4fe',
        },
    },
    {
        id: 'yellow',
        name: 'Vàng',
        color: '#d97706',
        vars: {
            '--color-primary': '#d97706',
            '--color-primary-hover': '#b45309',
            '--color-primary-light': '#fffbeb',
            '--color-primary-medium': '#fef3c7',
            '--color-primary-dark': '#92400e',
            '--color-primary-ring': '#f59e0b',
            '--color-gradient-from': '#f59e0b',
            '--color-gradient-to': '#ef4444',
            '--color-msg-sent': '#d97706',
            '--bg-main': '#fffbeb',
            '--bg-card': '#ffffff',
            '--bg-secondary': '#fef3c7',
            '--bg-input': '#ffffff',
            '--bg-hover': '#fef3c7',
            '--text-primary': '#111827',
            '--text-secondary': '#374151',
            '--text-tertiary': '#6b7280',
            '--border-color': '#fde68a',
            '--border-input': '#fcd34d',
        },
    },
    {
        id: 'brown',
        name: 'Nâu',
        color: '#92400e',
        vars: {
            '--color-primary': '#92400e',
            '--color-primary-hover': '#78350f',
            '--color-primary-light': '#fefce8',
            '--color-primary-medium': '#fef3c7',
            '--color-primary-dark': '#451a03',
            '--color-primary-ring': '#b45309',
            '--color-gradient-from': '#b45309',
            '--color-gradient-to': '#78350f',
            '--color-msg-sent': '#92400e',
            '--bg-main': '#fdf6e3',
            '--bg-card': '#fffef5',
            '--bg-secondary': '#fef3c7',
            '--bg-input': '#fffef5',
            '--bg-hover': '#fef3c7',
            '--text-primary': '#1c1917',
            '--text-secondary': '#44403c',
            '--text-tertiary': '#78716c',
            '--border-color': '#e7c98a',
            '--border-input': '#d6b06b',
        },
    },
    {
        id: 'dark',
        name: 'Đen (Dark)',
        color: '#1e293b',
        isDark: true,
        vars: {
            '--color-primary': '#818cf8',
            '--color-primary-hover': '#6366f1',
            '--color-primary-light': '#1e1b4b',
            '--color-primary-medium': '#312e81',
            '--color-primary-dark': '#c7d2fe',
            '--color-primary-ring': '#818cf8',
            '--color-gradient-from': '#6366f1',
            '--color-gradient-to': '#8b5cf6',
            '--color-msg-sent': '#6366f1',
            '--bg-main': '#0f172a',
            '--bg-card': '#1e293b',
            '--bg-secondary': '#1a2332',
            '--bg-input': '#0f172a',
            '--bg-hover': '#334155',
            '--text-primary': '#f1f5f9',
            '--text-secondary': '#94a3b8',
            '--text-tertiary': '#64748b',
            '--border-color': '#334155',
            '--border-input': '#475569',
            '--bg-error': 'rgba(239,68,68,0.15)',
            '--text-error': '#f87171',
        },
    },
    {
        id: 'light',
        name: 'Trắng (Light)',
        color: '#f8fafc',
        vars: {
            '--color-primary': '#6366f1',
            '--color-primary-hover': '#4f46e5',
            '--color-primary-light': '#eef2ff',
            '--color-primary-medium': '#e0e7ff',
            '--color-primary-dark': '#4338ca',
            '--color-primary-ring': '#818cf8',
            '--color-gradient-from': '#6366f1',
            '--color-gradient-to': '#a78bfa',
            '--color-msg-sent': '#6366f1',
            '--bg-main': '#f8fafc',
            '--bg-card': '#ffffff',
            '--bg-secondary': '#f1f5f9',
            '--bg-input': '#ffffff',
            '--bg-hover': '#f1f5f9',
            '--text-primary': '#111827',
            '--text-secondary': '#374151',
            '--text-tertiary': '#6b7280',
            '--border-color': '#e2e8f0',
            '--border-input': '#cbd5e1',
        },
    },
];

// Default light-mode neutral values (used as fallback in :root)
export const LIGHT_NEUTRALS = {
    '--bg-main': '#f9fafb',
    '--bg-card': '#ffffff',
    '--bg-secondary': '#f3f4f6',
    '--bg-input': '#ffffff',
    '--bg-hover': '#f3f4f6',
    '--text-primary': '#111827',
    '--text-secondary': '#6b7280',
    '--text-tertiary': '#9ca3af',
    '--border-color': '#e5e7eb',
    '--border-input': '#d1d5db',
    '--bg-error': '#fef2f2',
    '--text-error': '#dc2626',
};

export const DEFAULT_THEME = 'blue';
