/**
 * themes.js — Color theme definitions.
 *
 * Each theme defines CSS custom properties that are applied to <html>.
 * Components use these via Tailwind arbitrary values: bg-[var(--color-primary)]
 */

export const THEMES = [
    {
        id: 'blue',
        name: 'Xanh dương',
        color: '#2563eb',
        vars: {
            '--color-primary': '#2563eb',
            '--color-primary-hover': '#1d4ed8',
            '--color-primary-light': '#eff6ff',
            '--color-primary-medium': '#dbeafe',
            '--color-primary-dark': '#1e40af',
            '--color-primary-ring': '#3b82f6',
            '--color-gradient-from': '#6366f1',
            '--color-gradient-to': '#8b5cf6',
            '--color-msg-sent': '#2563eb',
            '--bg-main': '#eff6ff',
            '--bg-card': '#ffffff',
            '--bg-secondary': '#dbeafe',
            '--bg-input': '#ffffff',
            '--bg-hover': '#dbeafe',
            '--text-primary': '#111827',
            '--text-secondary': '#374151',
            '--text-tertiary': '#6b7280',
            '--border-color': '#bfdbfe',
            '--border-input': '#93c5fd',
        },
    },
    {
        id: 'red',
        name: 'Đỏ',
        color: '#dc2626',
        vars: {
            '--color-primary': '#dc2626',
            '--color-primary-hover': '#b91c1c',
            '--color-primary-light': '#fef2f2',
            '--color-primary-medium': '#fee2e2',
            '--color-primary-dark': '#991b1b',
            '--color-primary-ring': '#ef4444',
            '--color-gradient-from': '#ef4444',
            '--color-gradient-to': '#f97316',
            '--color-msg-sent': '#dc2626',
            '--bg-main': '#fef2f2',
            '--bg-card': '#ffffff',
            '--bg-secondary': '#fee2e2',
            '--bg-input': '#ffffff',
            '--bg-hover': '#fee2e2',
            '--text-primary': '#111827',
            '--text-secondary': '#374151',
            '--text-tertiary': '#6b7280',
            '--border-color': '#fecaca',
            '--border-input': '#fca5a5',
        },
    },
    {
        id: 'purple',
        name: 'Tím',
        color: '#9333ea',
        vars: {
            '--color-primary': '#9333ea',
            '--color-primary-hover': '#7e22ce',
            '--color-primary-light': '#faf5ff',
            '--color-primary-medium': '#f3e8ff',
            '--color-primary-dark': '#6b21a8',
            '--color-primary-ring': '#a855f7',
            '--color-gradient-from': '#a855f7',
            '--color-gradient-to': '#ec4899',
            '--color-msg-sent': '#9333ea',
            '--bg-main': '#faf5ff',
            '--bg-card': '#ffffff',
            '--bg-secondary': '#f3e8ff',
            '--bg-input': '#ffffff',
            '--bg-hover': '#f3e8ff',
            '--text-primary': '#111827',
            '--text-secondary': '#374151',
            '--text-tertiary': '#6b7280',
            '--border-color': '#e9d5ff',
            '--border-input': '#d8b4fe',
        },
    },
    {
        id: 'yellow',
        name: 'Vàng',
        color: '#d97706',
        vars: {
            '--color-primary': '#d97706',
            '--color-primary-hover': '#b45309',
            '--color-primary-light': '#fffbeb',
            '--color-primary-medium': '#fef3c7',
            '--color-primary-dark': '#92400e',
            '--color-primary-ring': '#f59e0b',
            '--color-gradient-from': '#f59e0b',
            '--color-gradient-to': '#ef4444',
            '--color-msg-sent': '#d97706',
            '--bg-main': '#fffbeb',
            '--bg-card': '#ffffff',
            '--bg-secondary': '#fef3c7',
            '--bg-input': '#ffffff',
            '--bg-hover': '#fef3c7',
            '--text-primary': '#111827',
            '--text-secondary': '#374151',
            '--text-tertiary': '#6b7280',
            '--border-color': '#fde68a',
            '--border-input': '#fcd34d',
        },
    },
    {
        id: 'brown',
        name: 'Nâu',
        color: '#92400e',
        vars: {
            '--color-primary': '#92400e',
            '--color-primary-hover': '#78350f',
            '--color-primary-light': '#fefce8',
            '--color-primary-medium': '#fef3c7',
            '--color-primary-dark': '#451a03',
            '--color-primary-ring': '#b45309',
            '--color-gradient-from': '#b45309',
            '--color-gradient-to': '#78350f',
            '--color-msg-sent': '#92400e',
            '--bg-main': '#fdf6e3',
            '--bg-card': '#fffef5',
            '--bg-secondary': '#fef3c7',
            '--bg-input': '#fffef5',
            '--bg-hover': '#fef3c7',
            '--text-primary': '#1c1917',
            '--text-secondary': '#44403c',
            '--text-tertiary': '#78716c',
            '--border-color': '#e7c98a',
            '--border-input': '#d6b06b',
        },
    },
    {
        id: 'dark',
        name: 'Đen (Dark)',
        color: '#1e293b',
        isDark: true,
        vars: {
            '--color-primary': '#818cf8',
            '--color-primary-hover': '#6366f1',
            '--color-primary-light': '#25244a',
            '--color-primary-medium': '#3b3a72',
            '--color-primary-dark': '#c7d2fe',
            '--color-primary-ring': '#818cf8',
            '--color-gradient-from': '#6366f1',
            '--color-gradient-to': '#8b5cf6',
            '--color-msg-sent': '#6366f1',
            '--bg-main': '#11192d',
            '--bg-card': '#1b2638',
            '--bg-secondary': '#192437',
            '--bg-input': '#141f32',
            '--bg-hover': '#27354a',
            '--text-primary': '#e6edf6',
            '--text-secondary': '#9db0c6',
            '--text-tertiary': '#7f93ab',
            '--border-color': '#314257',
            '--border-input': '#425770',
            '--bg-error': 'rgba(239,68,68,0.15)',
            '--text-error': '#f87171',
        },
    },
    {
        id: 'light',
        name: 'Trắng (Light)',
        color: '#f8fafc',
        vars: {
            '--color-primary': '#6366f1',
            '--color-primary-hover': '#4f46e5',
            '--color-primary-light': '#eef2ff',
            '--color-primary-medium': '#e0e7ff',
            '--color-primary-dark': '#4338ca',
            '--color-primary-ring': '#818cf8',
            '--color-gradient-from': '#6366f1',
            '--color-gradient-to': '#a78bfa',
            '--color-msg-sent': '#6366f1',
            '--bg-main': '#f8fafc',
            '--bg-card': '#ffffff',
            '--bg-secondary': '#f1f5f9',
            '--bg-input': '#ffffff',
            '--bg-hover': '#f1f5f9',
            '--text-primary': '#111827',
            '--text-secondary': '#374151',
            '--text-tertiary': '#6b7280',
            '--border-color': '#e2e8f0',
            '--border-input': '#cbd5e1',
        },
    },
    {
        id: 'midnight-purple',
        name: 'Tím Đêm',
        color: '#2d1b69',
        isDark: true,
        vars: {
            '--color-primary': '#a996e8',
            '--color-primary-hover': '#9581d8',
            '--color-primary-light': '#211444',
            '--color-primary-medium': '#32255f',
            '--color-primary-dark': '#d9d3ef',
            '--color-primary-ring': '#a996e8',
            '--color-gradient-from': '#7c3aed',
            '--color-gradient-to': '#c026d3',
            '--color-msg-sent': '#7c3aed',
            '--bg-main': '#110f27',
            '--bg-card': '#201b3e',
            '--bg-secondary': '#1b1737',
            '--bg-input': '#17132f',
            '--bg-hover': '#2f2755',
            '--text-primary': '#ddd7f2',
            '--text-secondary': '#b7a9df',
            '--text-tertiary': '#9585c4',
            '--border-color': '#3a2f63',
            '--border-input': '#50407f',
            '--bg-error': 'rgba(239,68,68,0.15)',
            '--text-error': '#f87171',
        },
    },
    {
        id: 'solarized',
        name: 'Solarized',
        color: '#268bd2',
        vars: {
            '--color-primary': '#268bd2',
            '--color-primary-hover': '#2176b3',
            '--color-primary-light': '#fdf6e3',
            '--color-primary-medium': '#eee8d5',
            '--color-primary-dark': '#073642',
            '--color-primary-ring': '#268bd2',
            '--color-gradient-from': '#268bd2',
            '--color-gradient-to': '#2aa198',
            '--color-msg-sent': '#268bd2',
            '--bg-main': '#fdf6e3',
            '--bg-card': '#fffcf0',
            '--bg-secondary': '#eee8d5',
            '--bg-input': '#fffcf0',
            '--bg-hover': '#eee8d5',
            '--text-primary': '#073642',
            '--text-secondary': '#586e75',
            '--text-tertiary': '#93a1a1',
            '--border-color': '#d6ceb2',
            '--border-input': '#c4bc99',
        },
    },
    {
        id: 'glassmorphism',
        name: 'Kính mờ',
        color: '#6366f1',
        isDark: true,
        vars: {
            '--color-primary': '#8794ea',
            '--color-primary-hover': '#7380da',
            '--color-primary-light': 'rgba(135,148,234,0.08)',
            '--color-primary-medium': 'rgba(135,148,234,0.16)',
            '--color-primary-dark': '#c8d2f1',
            '--color-primary-ring': '#8794ea',
            '--color-gradient-from': '#6366f1',
            '--color-gradient-to': '#06b6d4',
            '--color-msg-sent': '#6366f1',
            '--bg-main': '#11192d',
            '--bg-card': 'rgba(28,40,58,0.76)',
            '--bg-secondary': 'rgba(28,40,58,0.6)',
            '--bg-input': 'rgba(21,31,47,0.84)',
            '--bg-hover': 'rgba(56,70,94,0.48)',
            '--text-primary': '#e5edf7',
            '--text-secondary': '#a4b2c8',
            '--text-tertiary': '#8193aa',
            '--border-color': 'rgba(138,154,180,0.24)',
            '--border-input': 'rgba(138,154,180,0.34)',
            '--bg-error': 'rgba(239,68,68,0.15)',
            '--text-error': '#f87171',
        },
    },
    {
        id: 'retro-terminal',
        name: 'Terminal',
        color: '#22c55e',
        isDark: true,
        vars: {
            '--color-primary': '#3ac777',
            '--color-primary-hover': '#31b06a',
            '--color-primary-light': '#0d2919',
            '--color-primary-medium': '#1a402b',
            '--color-primary-dark': '#b7e7c7',
            '--color-primary-ring': '#3ac777',
            '--color-gradient-from': '#22c55e',
            '--color-gradient-to': '#10b981',
            '--color-msg-sent': '#2b8f5d',
            '--bg-main': '#07110a',
            '--bg-card': '#102016',
            '--bg-secondary': '#0d1a13',
            '--bg-input': '#09150e',
            '--bg-hover': '#214c36',
            '--text-primary': '#b2dfc2',
            '--text-secondary': '#8ac8a3',
            '--text-tertiary': '#68a984',
            '--border-color': '#2a5a43',
            '--border-input': '#357059',
            '--bg-error': 'rgba(239,68,68,0.15)',
            '--text-error': '#f87171',
        },
    },
    {
        id: 'pixel-art',
        name: 'Pixel Art 8-bit',
        color: '#f59e0b',
        vars: {
            '--color-primary': '#f59e0b',
            '--color-primary-hover': '#d97706',
            '--color-primary-light': '#fff7d6',
            '--color-primary-medium': '#fde68a',
            '--color-primary-dark': '#78350f',
            '--color-primary-ring': '#f59e0b',
            '--color-gradient-from': '#f59e0b',
            '--color-gradient-to': '#ef4444',
            '--color-msg-sent': '#f59e0b',
            '--bg-main': '#fef6e4',
            '--bg-card': '#fffaf0',
            '--bg-secondary': '#f5e3b3',
            '--bg-input': '#fffdf5',
            '--bg-hover': '#f7e7bc',
            '--text-primary': '#2b1e0f',
            '--text-secondary': '#4b3a20',
            '--text-tertiary': '#7c5e2e',
            '--border-color': '#d6b06b',
            '--border-input': '#c9973f',
            '--bg-error': '#fee2e2',
            '--text-error': '#b91c1c',
        },
    },
    {
        id: 'neon-night',
        name: 'Neon Night',
        color: '#22d3ee',
        isDark: true,
        vars: {
            '--color-primary': '#3bc6da',
            '--color-primary-hover': '#2eb2c6',
            '--color-primary-light': 'rgba(59,198,218,0.08)',
            '--color-primary-medium': 'rgba(59,198,218,0.14)',
            '--color-primary-dark': '#c9e7ef',
            '--color-primary-ring': '#3bc6da',
            '--color-gradient-from': '#22d3ee',
            '--color-gradient-to': '#fb7185',
            '--color-msg-sent': '#1f8ca4',
            '--bg-main': '#0a1022',
            '--bg-card': '#131d35',
            '--bg-secondary': '#17213b',
            '--bg-input': '#101a2f',
            '--bg-hover': '#223054',
            '--text-primary': '#d8f0f6',
            '--text-secondary': '#9ccad6',
            '--text-tertiary': '#7fb0bf',
            '--border-color': '#2b4673',
            '--border-input': '#3a5b90',
            '--bg-error': 'rgba(239,68,68,0.18)',
            '--text-error': '#fda4af',
        },
    },
];

// Default light-mode neutral values (used as fallback in :root)
export const LIGHT_NEUTRALS = {
    '--bg-main': '#f9fafb',
    '--bg-card': '#ffffff',
    '--bg-secondary': '#f3f4f6',
    '--bg-input': '#ffffff',
    '--bg-hover': '#f3f4f6',
    '--text-primary': '#111827',
    '--text-secondary': '#6b7280',
    '--text-tertiary': '#9ca3af',
    '--border-color': '#e5e7eb',
    '--border-input': '#d1d5db',
    '--bg-error': '#fef2f2',
    '--text-error': '#dc2626',
};

export const DEFAULT_THEME = 'blue';
